In [2]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [25]:
weights = np.array( [[1,2,3,4],[5,6,7,8],[9,10,11,12]], dtype=np.float32)
inputs = np.array([[0.1,0.2,0.3]], dtype=np.float32)
outs = np.dot(inputs, weights)


print ("Weights (Shape):\n", weights.shape)
print ("Weights:\n", weights)
print ("Inputs:\n", inputs)
print ("Dot Product:\n", dots)
print ("Output:\n", outs)

Weights (Shape):
 (3, 4)
Weights:
 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
Inputs:
 [[0.1 0.2 0.3]]
Dot Product:
 [1.4000001 2.6       5.        6.8      ]
Output:
 [[3.8000002 4.4       5.        5.6000004]]


In [21]:
# how its done in dot.sv
def dot(inputs,weights):
    outs = np.zeros(weights.shape[1], dtype=np.float32)
    for i in range(weights.shape[0]): # input length
        for j in range(weights.shape[1]): # output length
            outs[j] = outs[j] + weights[i][j] * inputs[i]
    return outs

# my results
print (dot(inputs[0],weights))
# reference results
print (outs[0])

[3.8000002 4.4       5.        5.6000004]
[3.8000002 4.4       5.        5.6000004]


In [15]:
import numpy as np
import struct

def flt_to_hex(f):
    return hex(struct.unpack('<I', struct.pack('<f', f))[0])

weights = np.array( [[1,2,3,4],[5,6,7,8],[9,10,11,12]], dtype=np.float32)
inputs = np.array([[0.1,0.2,0.3]], dtype=np.float32)
outs = np.dot(inputs, weights)
print ('localparam ROWS = %d,' %weights.shape[0])
print ('localparam COLS = %d,' %weights.shape[1])
print ()
print ('//weights:\n//' + str(weights).replace('\n', '\n//'))
#flts_str = list(map('"{:2.4f}"'.format, flts))
print ('localparam [31:0] weights [0:ROWS-1] [0:COLS-1] = \'{')
for i in range(weights.shape[0]):
    flts_hex = list(map(lambda x: '32\'h' + flt_to_hex(x)[2:], weights[i]))
    print ('\t\'{' + ','.join(flts_hex)  + '}', end='')
    print (',' if i < weights.shape[0]-1 else '')
print ('}')
    

localparam ROWS = 3,
localparam COLS = 4,

//weights:
//[[ 1.  2.  3.  4.]
// [ 5.  6.  7.  8.]
// [ 9. 10. 11. 12.]]
localparam [31:0] weights [0:ROWS-1] [0:COLS-1] = '{
	'{32'h3f800000,32'h40000000,32'h40400000,32'h40800000},
	'{32'h40a00000,32'h40c00000,32'h40e00000,32'h41000000},
	'{32'h41100000,32'h41200000,32'h41300000,32'h41400000}
}


In [ ]:
# Used in sim_dot testbench

In [23]:
import numpy as np
import struct

def flt_to_hex(f):
    return hex(struct.unpack('<I', struct.pack('<f', f))[0])

weights = np.array( [[1,2,3,4],[5,6,7,8],[9,10,11,12]], dtype=np.float32)
inputs = np.array([[0.1,0.2,0.3]], dtype=np.float32)
outs = np.dot(inputs, weights)

flts = inputs[0]
flts_hex = list(map(lambda x: '32\'h' + flt_to_hex(x)[2:], flts))
flts_str = list(map('"{:2.4f}"'.format, flts))
offset=6
print ('static bit [31:0] fpHex [0:' + str(len(flts)-1) + '] = {')
for i in range(0, len(flts), offset):
    print (' ' + ', '.join(flts_hex[i:i+offset] ), end='')
    print (',' if i < len(flts) - offset else ' ')
print ('};') 
print ('static string fpAscii [0:' + str(len(flts)-1) + '] = {')
for i in range(0, len(flts), offset):
    print (' ' + ', '.join(flts_str[i:i+offset]), end='')
    print (',' if i < len(flts) - offset else ' ')
print ('};')
print ('static int MAX_SIZE = %d;' % len(flts))  

static bit [31:0] fpHex [0:2] = {
 32'h3dcccccd, 32'h3e4ccccd, 32'h3e99999a 
};
static string fpAscii [0:2] = {
 "0.1000", "0.2000", "0.3000" 
};
static int MAX_SIZE = 3;


In [24]:
import numpy as np
import struct

def flt_to_hex(f):
    return hex(struct.unpack('<I', struct.pack('<f', f))[0])

weights = np.array( [[1,2,3,4],[5,6,7,8],[9,10,11,12]], dtype=np.float32)
inputs = np.array([[0.1,0.2,0.3]], dtype=np.float32)
outs = np.dot(inputs, weights)

flts = outs[0]
flts_hex = list(map(lambda x: '32\'h' + flt_to_hex(x)[2:], flts))
flts_str = list(map('"{:2.4f}"'.format, flts))
offset=6
print ('static bit [31:0] fpHex [0:' + str(len(flts)-1) + '] = {')
for i in range(0, len(flts), offset):
    print (' ' + ', '.join(flts_hex[i:i+offset] ), end='')
    print (',' if i < len(flts) - offset else ' ')
print ('};') 
print ('static string fpAscii [0:' + str(len(flts)-1) + '] = {')
for i in range(0, len(flts), offset):
    print (' ' + ', '.join(flts_str[i:i+offset]), end='')
    print (',' if i < len(flts) - offset else ' ')
print ('};')
print ('static int MAX_SIZE = %d;' % len(flts)) 

static bit [31:0] fpHex [0:3] = {
 32'h40733334, 32'h408ccccd, 32'h40a00000, 32'h40b33334 
};
static string fpAscii [0:3] = {
 "3.8000", "4.4000", "5.0000", "5.6000" 
};
static int MAX_SIZE = 4;
